---
- hosts: k8master  # Assuming you're running Ansible locally
  connection: local
  gather_facts: no  # Disable gathering facts
  become: yes
  vars:
    anisble_user: root

  tasks:

    - name: Apply manifest file using kubectl

      shell: kubectl apply -f /etc/kubernetes/kubernetes_deploy.yml
