- name: Deploy Kubernetes resources using manifest file
  hosts: localhost
  become: true
  tasks:
    - name: Check if Deployment exists
      command: kubectl get deployment abc-pod -n default
      register: existing_deployment
      ignore_errors: true

    - name: Delete Deployment if exists
      command: kubectl delete deployment abc-pod -n default
      when: existing_deployment.rc == 0

    - name: Check if Service exists
      command: kubectl get service abc-svc -n default
      register: existing_service
      ignore_errors: true

    - name: Delete Service if exists
      command: kubectl delete service abc-svc -n default
      when: existing_service.rc == 0

    - name: Apply manifest file using kubectl
      shell: kubectl apply -f /etc/kubernetes/manifest.yml
