---
- name: Build Docker image
  hosts: localhost
  tasks:
    - name: Build Docker image from Dockerfile
      become_user: root
      docker_image:
        name: kiranimg4:latest
        source: build
        build:
          pull: no
          path: .
          dockerfile: Dockerfile
