---
- name: k8 deployment
  hosts: k8master
  connection: local
  gather_facts: no  # Disable gathering facts
  become: yes
  vars:
    ansible_user: root  # Corrected the spelling of 'ansible_user'

  tasks:
    - name: Apply manifest file using kubectl
      shell: kubectl apply -f manifest.yml
